### ISSUE TITLE
Exception when importing after installing with setup.py

### ISSUE THREAD

**Issue by ssilburn** [jsallcock/pycis#2]
If I run python setup.py install to install the module (haven't tried with pip -e, perhaps I'm just doing it wrong), the module does not import because it tries to create directories inside the zipped installed module. Exception is:

***** pycis Setup ***** Creating config directory at:
C:\Users\ssilb\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\pycis-0.1-py3.5.egg\pycis\model\config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Users\ssilb\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\pycis-0.1-py3.5.egg\pycis\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Users\ssilb\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\pycis-0.1-py3.5.egg\pycis\paths.py", line 28, in <module>
  File "C:\Users\ssilb\AppData\Local\Enthought\Canopy\edm\envs\User\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\ssilb\AppData\Local\Enthought\Canopy\edm\envs\User\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\ssilb\AppData\Local\Enthought\Canopy\edm\envs\User\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ssilb\\AppData\\Local\\Enthought\\Canopy\\edm\\envs\\User\\lib\\site-packages\\pycis-0.1-py3.5.egg\\pycis'

I think this could be fixed either by putting the config directories etc in the user's home directory instead of the code directory (probably best?) or adding zip_safe = False to the setup arguments.

**Comment by jsallcock** [comment]
Hi Scott, i have removed the code that was generating the config folders, since they aren't being used anyway.

I tried:
```
python setup.py install
```
and
```
python setup.py develop
```
and they seem to be working okay now. Though using pip makes things easier to uninstall! I checked and the -e flag in the pip install is equivalent to specifying develop.

Let me know if things are working for you, thanks.
